
# See http://www.appveyor.com/docs/appveyor-yml for many more options
# From https://github.com/RamblingCookieMonster/PSStackExchange/blob/master/appveyor.yml

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

build: false

test_script:
# Test with native PS version
  - ps: Invoke-Pester -EnableExit 